### ISSUE TITLE
cover-view 里面的button 真机上渲染异常

### ISSUE THREAD

**Issue by guanyx** [wechat-miniprogram/kbone#33]
```html
<cover-view class="auth-user-dialog" v-if="isShowDialog">
    <cover-view class="dialog-content">
        <cover-view class="dialog-center">
            <cover-view class="dialog-title">登录提醒</cover-view>
            <cover-view class="dialog-desc">登录后才可以正常使用功能</cover-view>
        </cover-view>
        <cover-view class="dialog-btns">
            <button class="dialog-btn dialog-cancel" @click="cancelLogin">暂不登录</button>
            <button class="dialog-btn dialog-confirm" open-type="getUserInfo" @getuserinfo="onGotUserInfoBeforeBind" @error="onAuthError">立即登录</button>
        </cover-view>
    </cover-view>
</cover-view>
```

```css
.auth-user-dialog {
    position: fixed;
    left: 0;
    top: 0;
    z-index: 9999;
    height: 100%;
    width: 100%;
    background: rgba(0, 0, 0, .3);

    .dialog-content {
        position: absolute;
        width: 80%;
        top: 30%;
        left: 10%;
        background: #FFF;
        border-radius: 4px;
    }
    .dialog-btns {
        display: block;
        border-top: 1px solid #e5e5e5;
        position: relative;
        z-index: 999999;
    }
    .dialog-btn {
        width: 50%;
        display: inline-block;
        align-items: center;
        justify-content: center;
        font-size: 16px;
        position: relative;
        z-index: 999999;
    }
}
```

在模拟器上
![image](https://51nbimg.u51.com/aad9d1715e704f65ab99ec56fcc5380f.png)

在真机上
![image](https://51nbimg.u51.com/3895a96470724d5a8b582b43197d5a33.png)

可以看到，button其实是把内容撑开了，但是按钮文案并没有显示

另外：因为是从mpvue的项目迁移过来的，相同的代码在使用mpvue的时候并没有问题，猜测大概率还是因为kbone在渲染每一个内置的组件时都会包一个element引起的
